// <auto-generated />
using System;
using Domino.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domino.Persistences.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420191544_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domino.Domain.Entities.Classification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("FavorPoints")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<byte>("LastRoundCalculated")
                        .HasColumnType("tinyint");

                    b.Property<short>("LostGame")
                        .HasColumnType("smallint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<short>("PointsAgainst")
                        .HasColumnType("smallint");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<byte>("TotalPercentage")
                        .HasColumnType("tinyint");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<short>("WinGame")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("PlayerId", "TournamentId")
                        .IsUnique();

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Elo")
                        .HasColumnType("smallint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LostGame")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("WinGame")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL AND [Email] != ''");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Elo")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlaymateId")
                        .HasColumnType("int");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("PointsAccumulated")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("RemainingChips")
                        .HasColumnType("tinyint");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<bool>("WonBlock")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlaymateId");

                    b.HasIndex("TableId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("RoundNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RemainingChips")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<bool>("WonBlock")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<short?>("MaxPlayers")
                        .HasColumnType("smallint");

                    b.Property<byte?>("MaxRound")
                        .HasColumnType("tinyint");

                    b.Property<short>("MinPlayers")
                        .HasColumnType("smallint");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetPoint")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Domino.Domain.Entities.TournamentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("DorsalNumber")
                        .HasColumnType("smallint");

                    b.Property<bool>("PaymentFee")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("PlayerId", "TournamentId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Classification", b =>
                {
                    b.HasOne("Domino.Domain.Entities.Player", "Player")
                        .WithMany("Classifications")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domino.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Classificationes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Result", b =>
                {
                    b.HasOne("Domino.Domain.Entities.Player", "Player")
                        .WithMany("Results")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domino.Domain.Entities.Player", "Playmate")
                        .WithMany()
                        .HasForeignKey("PlaymateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domino.Domain.Entities.Table", "Table")
                        .WithMany("Results")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Playmate");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Round", b =>
                {
                    b.HasOne("Domino.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Rondas")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Table", b =>
                {
                    b.HasOne("Domino.Domain.Entities.Round", "Round")
                        .WithMany("Tables")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Domino.Domain.Entities.TournamentRegistration", b =>
                {
                    b.HasOne("Domino.Domain.Entities.Player", "Player")
                        .WithMany("Registration")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domino.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Registrations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Player", b =>
                {
                    b.Navigation("Classifications");

                    b.Navigation("Registration");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Round", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Table", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("Domino.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Classificationes");

                    b.Navigation("Registrations");

                    b.Navigation("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
